- name: variables from args
  hosts: local
  connection: local
  tasks:
  - name: print the cousre info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE}}, {{ DURATION }}, {{ Trainer }}"